name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Integration Testing
        run: 	docker compose -f docker-compose.yml -f docker-compose.integrationtest.yml up --build --quiet-pull --exit-code-from integrationtest
