name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker compose -f docker-compose.yml -f ./dockerTestingFiles/docker-compose.integrationtest.yml up -d --quiet-pull --build --remove-orphans --exit-code-from integrationtest 
