name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Testing
        run: 	docker compose -f ./dockerTestingFiles/docker-compose.unittest.yml up --quiet-pull --build --exit-code-from clubseek